config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('account.urls')),
    path('', include('dashboard.urls')),
    path('account/', include('account.api.urls')),
    
    # APIs
    path('api/dashboard/', include('dashboard.api.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/api/urls.py
from django.urls import path

from dashboard.api.views import FileMetadataAPIView, CommentDeleteAPIView


urlpatterns = [
    path('api/files/<int:pk>/metadata/', FileMetadataAPIView.as_view(), name='file_metadata_api'),
    path('api/comments/<int:pk>/delete/', CommentDeleteAPIView.as_view(), name='comment_delete_api'),
]

dashboard/urls.py
from django.urls import path

from dashboard.views import (
    FileListView, 
    FileUploadView, 
    FileDetailView, 
    FileDeleteView, 
    FileAccessByLinkView, 
    CommentDeleteView,
    FileEditView,
    HashtagFilesView,
    FileDownloadView
)


urlpatterns = [
    path('', FileListView.as_view(), name='file_list'),
    path('files/upload/', FileUploadView.as_view(), name='file_upload'),
    path('files/<int:pk>/', FileDetailView.as_view(), name='file_detail'),
    path('files/<int:pk>/delete/', FileDeleteView.as_view(), name='file_delete'),
    path('file/<str:unique_link>/', FileAccessByLinkView.as_view(), name='file_access_by_link'),
    path('file/<int:pk>/edit/', FileEditView.as_view(), name='file_edit'),
    path('file/<int:pk>/download/', FileDownloadView.as_view(), name='file_download'),

    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),


    path('hashtag/<int:pk>/', HashtagFilesView.as_view(), name='hashtag_files')
]

dashboard/models.py
import mimetypes

from django.core.cache import cache
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.crypto import get_random_string
from django.utils import timezone
from django.urls import reverse

from services.uploader import Uploader


User = get_user_model()


class Hashtag(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class File(models.Model):
    FILE_TYPES = [
        ('PNG', '.png'),
        ('DOC', '.doc'),
        ('PPTX', '.pptx')
    ]
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    file = models.FileField(upload_to=Uploader.upload_file)
    file_type = models.CharField(max_length=4, choices=FILE_TYPES)
    description = models.TextField(blank=True, null=True)
    hashtags = models.ManyToManyField(Hashtag, related_name='files')
    public = models.BooleanField(default=True)
    expiration_date = models.DateTimeField(blank=True, null=True)
    unique_link = models.CharField(max_length=255, unique=True, blank=True, null=True)
    views = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.file.name} owned by {self.owner.email}"
    
    def save(self, *args, **kwargs):
        if self.file:
            mime_type, _ = mimetypes.guess_type(self.file.name)
            if mime_type:
                if 'png' in mime_type:
                    self.file_type = 'PNG'
                elif 'msword' in mime_type or 'vnd.openxmlformats-officedocument.wordprocessingml.document' in mime_type:
                    self.file_type = 'DOC'
                elif 'vnd.openxmlformats-officedocument.presentationml.presentation' in mime_type:
                    self.file_type = 'PPTX'
        
        super().save(*args, **kwargs)

    def generate_unique_link(self):
        self.unique_link = get_random_string(32)
        self.save()

    def increment_views(self):
        cache_key = f'file_{self.id}_views'
        if cache.get(cache_key) is None:
            cache.set(cache_key, self.views, timeout=None)
        cache.incr(cache_key)

    def get_views(self):
        cache_key = f'file_{self.id}_views'
        return cache.get(cache_key, self.views)

    def has_expired(self):
        return self.expiration_date and timezone.now() > self.expiration_date

    def delete_if_expired(self):
        if self.has_expired():
            self.delete()

    def get_absolute_url(self):
        return reverse('file-detail', kwargs={'pk': self.pk})

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    file = models.ForeignKey(File, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment by {self.user.email} on {self.file.file.name}"

    def delete_comment(self):
        if self.user == self.file.owner or self.user == self:
            self.delete()

    class Meta:
        ordering = ['-created_at']

dashboard/forms.py
import mimetypes

from django import forms

from dashboard.models import File, Hashtag, Comment


class FileForm(forms.ModelForm):
    new_hashtags = forms.CharField(
        required=False,
        help_text="Separate new hashtags with commas.",
        widget=forms.TextInput(attrs={'placeholder': 'Add new hashtags'}),
    )

    class Meta:
        model = File
        fields = ['file', 'description', 'hashtags', 'public', 'expiration_date']
        widgets = {
            'expiration_date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    def clean_file(self):
        uploaded_file = self.cleaned_data.get('file')
        allowed_file_types = ['image/png', 'application/msword', 'application/vnd.openxmlformats-officedocument.presentationml.presentation']
        
        mime_type, encoding = mimetypes.guess_type(uploaded_file.name)
        
        if mime_type not in allowed_file_types:
            raise forms.ValidationError("Unsupported file type. Please upload .png, .doc, or .pptx files.")
        
        return uploaded_file

    def save(self, commit=True):
        instance = super().save(commit=False)

        if self.user:
            instance.owner = self.user

        if commit:
            instance.save()

        new_hashtags = self.cleaned_data.get('new_hashtags', '')
        new_hashtag_objects = []
        if new_hashtags:
            hashtag_names = [tag.strip() for tag in new_hashtags.split(',') if tag.strip()]
            for tag_name in hashtag_names:
                hashtag, created = Hashtag.objects.get_or_create(name=tag_name)
                new_hashtag_objects.append(hashtag)
                print(f"Hashtag created: {hashtag.name}, Added to file: {instance.file.name}")

        selected_hashtags = self.cleaned_data.get('hashtags')
        combined_hashtags = list(selected_hashtags) + new_hashtag_objects
        instance.hashtags.set(combined_hashtags)

        return instance


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

dashboard/api/views.py
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework import status

from django.shortcuts import get_object_or_404

from dashboard.models import File, Comment
from dashboard.api.serializers import FileSerializer


class FileMetadataAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, pk, *args, **kwargs):
        file = get_object_or_404(File, pk=pk)
        if file.owner != request.user:
            return Response({'error': 'Permission denied'}, status=status.HTTP_403_FORBIDDEN)

        serializer = FileSerializer(file)
        return Response(serializer.data)


class CommentDeleteAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def delete(self, request, pk, *args, **kwargs):
        comment = get_object_or_404(Comment, pk=pk)
        if request.user == comment.user or request.user == comment.file.owner:
            comment.delete()
            return Response(status=status.HTTP_204_NO_CONTENT)
        return Response({'error': 'Permission denied'}, status=status.HTTP_403_FORBIDDEN)

dashboard/views.py
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponseForbidden, HttpResponse
from django.views import View
from django.views.generic import (
    ListView, 
    CreateView, 
    DetailView, 
    DeleteView, 
    UpdateView
)
from django.contrib.auth.mixins import LoginRequiredMixin

from dashboard.models import File, Comment, Hashtag
from dashboard.forms import FileForm, CommentForm


class FileListView(ListView):
    model = File
    template_name = 'dashboard/file_list.html'
    context_object_name = 'files'

    def get_queryset(self):
        return File.objects.filter(public=True)

class FileAccessByLinkView(DetailView):
    model = File
    template_name = 'dashboard/file_detail.html'
    context_object_name = 'file'

    def get_object(self, queryset=None):
        return get_object_or_404(File, unique_link=self.kwargs['unique_link'])

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.increment_views()
        return super().get(request, *args, **kwargs)

class FileUploadView(LoginRequiredMixin, CreateView):
    model = File
    form_class = FileForm
    template_name = 'dashboard/file_upload.html'
    success_url = reverse_lazy('file_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        file = form.save()
        file.generate_unique_link()         
        file.save()
        form.save_m2m()
        return super().form_valid(form)


class FileDetailView(DetailView):
    model = File
    template_name = 'dashboard/file_detail.html'
    context_object_name = 'file'

    def get_context_data(self, **kwargs):
        # Increment file views and add comments to context
        self.object.increment_views()
        context = super().get_context_data(**kwargs)
        context['comments'] = self.object.comments.all()
        context['form'] = CommentForm()
        context['views'] = self.object.get_views()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = CommentForm(request.POST)
        if form.is_valid() and request.user.is_authenticated:
            comment = form.save(commit=False)
            comment.user = request.user
            comment.file = self.object
            comment.save()
            return redirect('file_detail', pk=self.object.pk)
        return self.get(request, *args, **kwargs)


class FileDeleteView(LoginRequiredMixin, DeleteView):
    model = File
    template_name = 'dashboard/file_confirm_delete.html'
    success_url = reverse_lazy('file_list') 

    def dispatch(self, request, *args, **kwargs):
        file = self.get_object()
        if file.owner != request.user:
            return HttpResponseForbidden()
        return super().dispatch(request, *args, **kwargs)


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment
    success_url = reverse_lazy('file_list')

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(user=self.request.user) | qs.filter(file__owner=self.request.user)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        file_id = self.object.file.id
        success_url = reverse_lazy('file_detail', kwargs={'pk': file_id})
        self.object.delete()
        return redirect(success_url)


class FileEditView(LoginRequiredMixin, UpdateView):
    model = File
    form_class = FileForm
    template_name = 'dashboard/file_edit.html'
    success_url = reverse_lazy('file_list')

    def get_queryset(self):
        return File.objects.filter(owner=self.request.user)
    

class FileDownloadView(View):
    def get(self, request, pk, *args, **kwargs):
        file_instance = get_object_or_404(File, pk=pk)
        response = HttpResponse(file_instance.file.open(), content_type='application/octet-stream')
        response['Content-Disposition'] = f'attachment; filename="{file_instance.file.name}"'
        return response


class HashtagFilesView(ListView):
    model = File
    template_name = 'dashboard/hashtag_files.html'
    context_object_name = 'files'
    
    def get_queryset(self):
        self.hashtag = get_object_or_404(Hashtag, pk=self.kwargs['pk'])
        return File.objects.filter(hashtags=self.hashtag)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['hashtag'] = self.hashtag
        return context

templates/dashboard/file_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}File Details{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/file_detail.css' %}">
{% endblock %}

{% block content %}
<div class="detail-container">
    <!-- File Information -->
    <div class="file-card">
        <h2>{{ file.file.name }}</h2>
        <p><strong>Description:</strong> {{ file.description }}</p>
        <p><strong>Hashtags:</strong> 
            {% for tag in file.hashtags.all %}
                <a href="{% url 'hashtag_files' tag.id %}" class="hashtag">{{ tag.name }}</a>
            {% empty %}
                <span>No hashtags added</span>
            {% endfor %}
        </p>
        <p><strong>Views:</strong> {{ views }}</p>
        <p><strong>Expiration:</strong> {{ file.expiration_date|date:"Y-m-d H:i" }}</p>
        <p><strong>Owner:</strong> {{ file.owner }}</p>

        <!-- Edit and Delete Buttons for the File Owner -->
        {% if request.user == file.owner %}
        <div class="file-actions mb-3">
            <a href="{% url 'file_edit' file.pk %}" class="edit-btn">Edit</a>
            <form action="{% url 'file_delete' file.pk %}" method="POST" style="display:inline;">
                {% csrf_token %}
                <button type="submit" class="delete-btn">Delete</button>
            </form>
        </div>
        {% endif %}
        <a href="{% url 'file_download' file.pk %}" class="download-btn">Download File</a>
    </div>

    <!-- Comments Section -->
    <div class="comments-section">
        <h3>Comments</h3>
        <ul class="comment-list">
            {% for comment in comments %}
                <li>
                    <strong>{{ comment.user.email }}</strong>:
                    {{ comment.text }}
                    <span class="comment-date">{{ comment.created_at|date:"Y-m-d H:i" }}</span>
                    
                    <!-- Show delete button if the comment belongs to the user or file owner -->
                    {% if request.user == comment.user or request.user == file.owner %}
                        <form action="{% url 'comment_delete' comment.pk %}" method="POST" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="delete-comment-btn">Delete</button>
                        </form>
                    {% endif %}
                </li>
            {% empty %}
                <li>No comments yet. Be the first to comment!</li>
            {% endfor %}
        </ul>
    </div>

    <!-- Add Comment Form (for logged-in users) -->
    {% if user.is_authenticated %}
    <div class="comment-form">
        <h3>Add a Comment</h3>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="submit-btn">Post Comment</button>
        </form>
    </div>
    {% endif %}
</div>
{% endblock %}

templates/dashboard/file_edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Edit File{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/file_edit.css' %}">
{% endblock %}

{% block content %}
<div class="edit-container">
    <h2>Edit File</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="submit-btn">Save Changes</button>
    </form>
</div>
{% endblock %}

templates/dashboard/file_list.html
{% extends 'base.html' %}
{% block content %}
  <h1>Public Files</h1>
  <ol>
    {% for file in files %}
      <li class='d-flex justify-content-between mb-3'>
        <div>
          <a href="{% url 'file_detail' file.pk %}">{{ file.file.name }}</a> - Views: {{ file.get_views }}  
        </div>
          
        <div>
          <a href="{% url 'file_download' file.pk %}" class="download-btn">Download File</a>
        </div>
      </li>
    {% endfor %}
  </ol>
{% endblock %}

templates/dashboard/file_upload.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Upload New File{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/file_upload.css' %}">
{% endblock %}

{% block content %}
<div class="upload-container">
    <div class="upload-card">
        <h2 class="upload-title">Upload Your File</h2>

        <!-- Display form errors -->
        {% if form.errors %}
            <div class="form-errors">
                <ul>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ field.label }}: {{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        
        <!-- Upload form -->
        <form method="POST" enctype="multipart/form-data" class="upload-form">
            {% csrf_token %}

            <!-- Custom file input -->
            <div class="form-group custom-file-input">
                <label for="id_file" class="file-label">Choose File</label>
                <input type="file" id="id_file" name="file" required>
                <span id="file-label-text">No file chosen</span>
            </div>

            <!-- Description input -->
            <div class="form-group">
                <label for="id_description">Description</label>
                {{ form.description }}
            </div>            

            <!-- Hashtags multi-select -->
            <div class="form-group">
                <label for="id_hashtags">Select Existing Hashtags</label>
                {{ form.hashtags }}
            </div>

            <!-- New Hashtags input -->
            <div class="form-group">
                <label for="id_new_hashtags">Add New Hashtags</label>
                {{ form.new_hashtags }}
            </div>

            <!-- Public/Private checkbox -->
            <div class="form-group visibility-group">
                <label for="id_public">Visibility</label>
                {{ form.public }}
            </div>

            <!-- Expiration date input -->
            <div class="form-group">
                <label for="id_expiration_date">Expiration Date</label>
                {{ form.expiration_date }}
            </div>

            <!-- Submit button -->
            <button type="submit" class="submit-btn">Upload File</button>
        </form>
    </div>
</div>
{% endblock %}

templates/dashboard/hashtag_files.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Files Tagged "{{ hashtag.name }}"{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/hashtag_files.css' %}">
{% endblock %}

{% block content %}
<div class="hashtag-container">
    <h2>Files Tagged "{{ hashtag.name }}"</h2>
    <ul class="file-list">
        {% for file in files %}
            <li>
                <a href="{% url 'file_detail' file.pk %}">{{ file.file.name }}</a> - {{ file.description }}
            </li>
        {% empty %}
            <li>No files found with this hashtag.</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/dashboard/index.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
{% endblock %}

{% block content %}
<div class="dashboard">
    <div class="sidebar">
        <a href="{% url 'file_upload' %}">Upload Files</a>
        <a href="{% url 'user_profile' %}">Profile</a>
    </div>
    <div class="content">
        <h2>Welcome, {{ user.email }}</h2>
        <p>Your dashboard content goes here.</p>
    </div>
</div>
{% endblock %}